version: "3.9"
services:
  postgres:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 5432:5432
  # postgres_test:
  #   container_name: ${TEST_DB_CONTAINER_NAME}
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=username
  #     - POSTGRES_USER=username
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "8081:5432"
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

