version: "3.9"
services:
  postgres:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA="/app/db_data/pgdata"
    volumes:
      - ./db_data:/app/db_data
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - APP_CONTAINER_NAME=${APP_CONTAINER_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

